name: Generate Snake Animation

on:
  # Schedule the action to run at a specific time (e.g., daily)
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  # Allows the workflow to run manually from the Actions tab
  workflow_dispatch:
  # Run the workflow when a new commit is pushed to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: stalker0418  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg  # Correct output path

      # Ensure the output directory exists (if not created by previous step)
      - name: Ensure Output Directory Exists
        run: mkdir -p dist

      # Push the generated snake.svg to the output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: true
          jekyll: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Ensure this matches your secret name
